{
  "formatVersion": "1.1",
  "component": {
    "group": "com.samsung.lwe.escargot",
    "module": "escargot-android",
    "version": "4.2.0.20250530.0.62e6e01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "escargot-android-4.2.0.20250530.0.62e6e01.aar",
          "url": "escargot-android-4.2.0.20250530.0.62e6e01.aar",
          "size": 6650222,
          "sha512": "b0f0d1a03fcd45a2115e3bbfb5d1374dac6c7ba283f400dc0277d103df2cb3efe85cbb9996d65af9d8c86d403814fa5a9d5bf4e5c2020ab34ae3339327a7ba79",
          "sha256": "7f5f5e25691902f03135c0bfa27217ba5e29c7ba8459dc95fca8e011729f7ab6",
          "sha1": "2d9a34e2eba5aca8e6e4dcca0f995acd249d8c84",
          "md5": "02b5f1dc418e003190f84fd773fdddfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "escargot-android-4.2.0.20250530.0.62e6e01.aar",
          "url": "escargot-android-4.2.0.20250530.0.62e6e01.aar",
          "size": 6650222,
          "sha512": "b0f0d1a03fcd45a2115e3bbfb5d1374dac6c7ba283f400dc0277d103df2cb3efe85cbb9996d65af9d8c86d403814fa5a9d5bf4e5c2020ab34ae3339327a7ba79",
          "sha256": "7f5f5e25691902f03135c0bfa27217ba5e29c7ba8459dc95fca8e011729f7ab6",
          "sha1": "2d9a34e2eba5aca8e6e4dcca0f995acd249d8c84",
          "md5": "02b5f1dc418e003190f84fd773fdddfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "escargot-android-4.2.0.20250530.0.62e6e01-sources.jar",
          "url": "escargot-android-4.2.0.20250530.0.62e6e01-sources.jar",
          "size": 13361,
          "sha512": "0eb34ed2dff9b7865ad3267f02d743e13ae80087659048cbc83ab931f5ee8bb84edbea99e827b495ce05d736a760c3657ffcef964b160c65df56bef11bad1136",
          "sha256": "04d43de048031632c756fe071e720e6487d5cb18f69882b1933dc226621a992a",
          "sha1": "c6b9c9fb14106f903076898575ae71f812c85794",
          "md5": "cca46663ae44fdf594cacde1c177381c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "escargot-android-4.2.0.20250530.0.62e6e01-javadoc.jar",
          "url": "escargot-android-4.2.0.20250530.0.62e6e01-javadoc.jar",
          "size": 400766,
          "sha512": "e8585e57f226784bfb36403fbc07cfdb146e77e12531fbe76d06a9852241a92aa2217f4f2b80d70675e2d8414d5f24b996919e07753fe5aaefe0653b0b676881",
          "sha256": "c0635df6d4216dc6b70506504b7deedaaa715550046ad6b1388699be6b9f3804",
          "sha1": "743e34f8c668ab160cdc85c42c794caddce34c92",
          "md5": "99712cd1369939e135431ecc1674eee7"
        }
      ]
    }
  ]
}
