#!/usr/bin/env python3
#
# Copyright (c) 2026-present Samsung Electronics Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Extracts the "S" (simple) case folding mappings from CaseFolding.txt.
#
# A code point gets an S entry exactly when its full ("F") case folding is more
# than one code point *and* Unicode still defines a single code point simple
# folding for it -- U+1FD3 folds fully to <03B9 0308 0301> but simply to U+0390,
# U+FB05 folds fully to "st" but simply to U+FB06, and so on.
#
# ECMAScript's Canonicalize() uses the simple mapping (ES2015+ 21.2.2.8.2), so
# the two code points of each such mapping have to match each other under /ui.
# Not every ICU reports that through uset_closeOver() / u_foldCase(), so Yarr
# links them from this table instead of trusting the runtime ICU.

import optparse
import os
import sys

header = """/*
 * Copyright (c) 2026-present Samsung Electronics Co., Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT! - This file was generated by """ + os.path.basename(__file__) + """
// from CaseFolding.txt ("S" mappings). See the generator for why this table exists.

#pragma once

namespace JSC {
namespace Yarr {

// Both directions of every simple case folding mapping whose full mapping is a
// multi code point string, sorted by `code` so it can be searched in log time.
struct SimpleCaseFoldingPair {
    char32_t code;
    char32_t counterpart;
};

"""


def parseSimpleFoldings(caseFoldingPath):
    pairs = set()
    with open(caseFoldingPath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.split('#', 1)[0].strip()
            if not line:
                continue
            fields = [field.strip() for field in line.split(';')]
            if len(fields) < 3 or fields[1] != 'S':
                continue
            code = int(fields[0], 16)
            fold = int(fields[2], 16)
            if code == fold:
                continue
            pairs.add((code, fold))
            pairs.add((fold, code))
    return sorted(pairs)


def dumpTable(outputFile, pairs):
    outputFile.write("static const SimpleCaseFoldingPair simpleCaseFoldingPairs[{}] = {{\n".format(len(pairs)))
    for code, counterpart in pairs:
        outputFile.write("    {{ 0x{:04X}, 0x{:04X} }},\n".format(code, counterpart))
    outputFile.write("};\n\n")
    outputFile.write("static const unsigned simpleCaseFoldingPairCount = {};\n\n".format(len(pairs)))
    outputFile.write("} // namespace Yarr\n} // namespace JSC\n")


if __name__ == "__main__":
    parser = optparse.OptionParser(usage="usage: %prog <UCD-Directory> <SimpleCaseFoldingTable.h>")
    (options, args) = parser.parse_args()

    if len(args) != 2:
        parser.error("<UCD-Directory> <SimpleCaseFoldingTable.h>")

    caseFoldingPath = os.path.join(args[0], "CaseFolding.txt")
    if not os.path.exists(caseFoldingPath):
        print("Couldn't find UCD file CaseFolding.txt at {0}".format(caseFoldingPath))
        sys.exit(1)

    pairs = parseSimpleFoldings(caseFoldingPath)
    if not pairs:
        print("No \"S\" mappings found in {0}".format(caseFoldingPath))
        sys.exit(1)

    with open(args[1], "w", encoding="UTF-8") as outputFile:
        outputFile.write(header)
        dumpTable(outputFile, pairs)

    sys.exit(0)
