#!/usr/bin/env python3

# Copyright (C) 2017-2023 Apple Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This tool extracts sequence property names from emoji-sequences.txt and
# emoji-zwj-sequences.txt to generate a minimal header for runtime ICU lookup.
# Hash tables and pattern arrays have been replaced by ICU runtime APIs
# (u_getPropertyEnum, u_getPropertyValueEnum, uset_openPattern).

import optparse
import os
import sys

header = """/*
* Copyright (C) 2017-2023 Apple Inc. All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1.  Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
* 2.  Redistributions in binary form must reproduce the above copyright
*     notice, this list of conditions and the following disclaimer in the
*     documentation and/or other materials provided with the distribution.
*
* THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
* EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// DO NO EDIT! - This file was generated by """ + __file__ + """
"""

footer = """
"""

RequiredUCDFiles = ["emoji-sequences.txt", "emoji-zwj-sequences.txt"]

UCDDirectoryPath = None


def openOrExit(path, mode):
    try:
        return open(path, mode, encoding="UTF-8")
    except IOError as e:
        print("I/O error opening {0}, ({1}): {2}".format(path, e.errno, e.strerror))
        exit(1)


def openUCDFileOrExit(path):
    if not UCDDirectoryPath:
        exit(1)
    return openOrExit(os.path.join(UCDDirectoryPath, path), 'r')


def verifyUCDFilesExist():
    if not UCDDirectoryPath:
        exit(1)
    missingFileCount = 0
    for file in RequiredUCDFiles:
        fullPath = os.path.join(UCDDirectoryPath, file)
        if not os.path.exists(fullPath):
            print("Couldn't find UCD file {0} at {1}".format(file, fullPath))
            missingFileCount = missingFileCount + 1
    if missingFileCount:
        exit(1)


def extractSequencePropertyNames(ucdDir):
    """Extract sequence property names from emoji-sequences.txt + emoji-zwj-sequences.txt.

    The type_field (second semicolon-separated field) contains the property name.
    RGI_Emoji is a union property not present in the txt files, so it is added separately.
    """
    names = set()
    for filename in ["emoji-sequences.txt", "emoji-zwj-sequences.txt"]:
        filepath = os.path.join(ucdDir, filename)
        if not os.path.isfile(filepath):
            continue
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.split('#', 1)[0].strip()
                if not line:
                    continue
                fields = line.split(';')
                if len(fields) < 2:
                    continue
                typeField = fields[1].strip()
                if typeField:
                    names.add(typeField)
    names.add("RGI_Emoji")  # union property
    return sorted(names)


def dumpSequencePropertyNames(file, names):
    file.write("// Sequence property names extracted from emoji-sequences.txt + emoji-zwj-sequences.txt\n")
    file.write("// RGI_Emoji is a union property (not in txt files, added separately)\n")
    file.write("static const char* const sequencePropertyNames[{}] = {{\n".format(len(names)))
    for name in names:
        file.write("    \"{}\",\n".format(name))
    file.write("};\n\n")

    file.write("static bool isSequencePropertyName(const WTF::String& name)\n")
    file.write("{\n")
    file.write("    if (name.isNull() || !name.is8Bit())\n")
    file.write("        return false;\n")
    file.write("    for (const char* seqName : sequencePropertyNames) {\n")
    file.write("        size_t seqLen = strlen(seqName);\n")
    file.write("        if (name.length() == seqLen && memcmp(name.characters8(), seqName, seqLen) == 0)\n")
    file.write("            return true;\n")
    file.write("    }\n")
    file.write("    return false;\n")
    file.write("}\n")


if __name__ == "__main__":
    parser = optparse.OptionParser(usage="usage: %prog <UCD-Directory> <UnicodePatternTables.h>")
    (options, args) = parser.parse_args()

    if len(args) != 2:
        parser.error("<UCD-Directory> <UnicodePatternTables.h>")

    UCDDirectoryPath = args[0]
    outputFilePath = args[1]

    verifyUCDFilesExist()

    sequencePropertyNames = extractSequencePropertyNames(UCDDirectoryPath)

    outputFile = openOrExit(outputFilePath, "w")
    outputFile.write(header)
    dumpSequencePropertyNames(outputFile, sequencePropertyNames)
    outputFile.write(footer)
    outputFile.close()

    exit(0)
