name: Android-Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-android-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK
      uses: actions/setup-java@v4.1.0
      with:
        distribution: "zulu"
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      working-directory: ./build/android
      run: |
        ./gradlew bundleHostJar
        ./gradlew javadocJar
        ./gradlew sourcesJar
        ./gradlew :escargot:testDebugUnitTest
        mv ./escargot/build/libs/escargot.jar ./escargot/build/libs/escargot-ubuntu.jar
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact-ubuntu
        path: |
          ./build/android/escargot/build/**/escargot-*.aar
          ./build/android/escargot/build/**/escargot-*.jar
          !./build/android/escargot/build/**/escargot-*Shell.aar
        if-no-files-found: error

  build-android-on-macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Packages
      run: |
        brew update
        brew install ninja icu4c
    - name: Set up JDK
      uses: actions/setup-java@v4.1.0
      with:
        distribution: "zulu"
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      working-directory: ./build/android
      run: |
        ./gradlew bundleHostJar
        ./gradlew :escargot:testDebugUnitTest
        mv ./escargot/build/libs/escargot.jar ./escargot/build/libs/escargot-mac.jar
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact-mac
        path: |
          ./build/android/escargot/build/libs/escargot-mac.jar
        if-no-files-found: error

  merge-update-release:
    needs: [build-android-on-ubuntu, build-android-on-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: build-artifact-*
        merge-multiple: true
    - name: Set release date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> $GITHUB_ENV
    - name: Merge build artifacts
      working-directory: ./artifacts
      run: |
        ls -R ./
        echo ${RELEASE_DATE}
        find . -type f -name "escargot-*.aar" -exec mv {} . \;
        find . -type f -name "escargot-*.jar" -exec mv {} . \;
        ls -R ./
        find ./ -type f -name "escargot-*.aar" -o -name "escargot-*.jar" | zip Android-Release-${{ env.RELEASE_DATE }}.zip -@
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/Android-Release-${{ env.RELEASE_DATE }}.zip
